#!/usr/bin/env bash
# This script is displaying displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School for the other iterations.

counter=0
while [ $counter -lt 10 ]; do
	(( counter+=1 ))
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		"Best School"
	fi
done
